branches:
  only:
    - "master"
language: node_js
node_js:
  - '9'
  - '8'
cache:
  directories:
  - node_modules
script:
  - npm run build
  - npm run test:cov

after_success: npx codecov --file=./coverage/lcov.info